version: '3.7'
services:
    src:
        build: ./src/
        tty: true
        ports:
            - "10218:8081"
        ulimits:
            nproc: 64
        deploy:
            resources:
              limits:
                cpus: '0.50'
                memory: 4096M